baseURL = "https://rrsharp122.github.io/"
languageCode = "en-us"
title = "Rachel Sharp"
theme = "PaperMod"

[params]
  showFullTextInList = true
  defaultTheme = "auto"

[params.assets]
  disableHLJS = true

[params.cdns]
  lucideReact = "https://cdnjs.cloudflare.com/ajax/libs/lucide-react/0.263.1/lucide-react.min.js"

[markup.goldmark.renderer]
  unsafe = true

[build]
  writeStats = true

[menu]
  [[menu.main]]
    identifier = "writing"
    name = "Writing Portfolio"
    url = "/writing/"
    weight = 10
  
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
  
  [[menu.main]]
    identifier = "research"
    name = "Research"
    url = "/research/"
    weight = 30
